basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Golang API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: GetUsers returns a list of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Get list of users
      tags:
      - users
swagger: "2.0"
