name: Deploy app to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.2'

    - name: Install dependencies
      run: go mod tidy

    - name: Check if swag is installed
      id: swag-check
      run: |
        if ! command -v swag &> /dev/null; then
          echo "Swag not found, installing..."
          go install github.com/swaggo/swag/cmd/swag@latest
        else
          echo "Swag is already installed"
        fi

    - name: Generate Swagger docs
      run: swag init -g ./cmd/api/main.go

    - name: Build
      run: go build -o main ./cmd/api

    - name: Setup Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
        echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
        echo "machine git.heroku.com" >> ~/.netrc
        echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
        echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
        heroku git:remote -a ${{ env.HEROKU_APP_NAME }}

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: todo-list-go-api
      run: |
        git remote add heroku https://git.heroku.com/${{ env.HEROKU_APP_NAME }}.git
        git push heroku main
