name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.2'

    - name: Check if swag is installed
      id: swag-check
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate Swagger docs
      run: swag init -g ./cmd/api/main.go

    - name: Install dependencies
      run: go mod tidy
      
    - name: Build
      run: go build -o main ./cmd/api

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "todo-list-go-api"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        usedocker: false